### ISSUE TITLE
View All Requests

### ISSUE THREAD

**Issue by obsidiangroup** [WillFantom/OverCLIrr#3]
First, I am not sure if this project is still active, but.

Would it be possible to add a command to view all requests, not just the requests for the current profile user.  This would make this a valuable tool.  Otherwise, in order to manage all requests you still have to use the webui.

**Comment by WillFantom** [comment]
I am happy to look into fixing this, perhaps supporting a flag to get all requests by any user and opportunistically fetching all visible based on the user's permissions. 

Although, are you currently using the API key for auth, or plex/local logins?

**Comment by obsidiangroup** [comment]
I am using the API key for auth.  It's funny, I'm looking through the code (and I am by no means a Go developer), and I see:
```
		if !allRequests {
			r, p, err := overseerr.GetUserRequests(me.ID, reqPage-1, reqPageSize)
			if err != nil {
				ui.Fatal("Could not get the request list for the current user", err)
			}
			requests = r
			pageInfo = p
		} else {
			r, p, err := overseerr.GetRequests(reqPage-1, reqPageSize, goverseerr.RequestFileterAll, goverseerr.RequestSortAdded)
			if err != nil {
				ui.Fatal("Could not get the full request list", err)
			}
			requests = r
			pageInfo = p
		}
```
So it seems that code to view all requests is already there, and looking at this:
```
func init() {
	requestsCmd.Flags().IntVarP(&reqPage, "page", "p", 1, "Which page of requests to view")
	requestsCmd.Flags().IntVar(&reqPageSize, "page-size", 20, "How many requests to show per page")
	requestsCmd.Flags().BoolVarP(&allRequests, "all", "a", false, "Attempt to get all requests, not just cirrent user's")
	RootCmd.AddCommand(requestsCmd)
	RootCmd.AddCommand(requestsAllCmd)
}
```
Tells me the flag -all is already there.  When testing adding the -all, all requests were displayed.

I was all ready to jump in and try to implement this myself -- setup Visual Studio Code for go development, already starting reading on Cobra, and run across this.  So I'm going to close this.  Maybe had I done 'overclirr requests --help' I would have saw this.
